# Generated by Django 3.1.4 on 2020-12-24 13:29

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_uniq_user_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=post.models.LowercaseEmailField(max_length=254, null=True, unique=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[post.models.phone_validate], verbose_name='شماره تلفن'),
        ),
    ]
