# Generated by Django 3.1.4 on 2020-12-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_uniq_user_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
